name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "task_one" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Compile maven
        run: mvn clean compile

  checkstyle:
    runs-on: ubuntu-latest
#    needs: build

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Checkstyle code
        run: mvn checkstyle:check

  tests:
    runs-on: ubuntu-latest
#    needs: build

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run Coverage
        run: |
          chmod +x gradlew
          ./gradlew testCoverage
      - name: Run tests
        run: mvn clean install
      - uses: madrapps/jacoco-report@v1.2
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 50


  deploy:
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        run: echo hello!